name: Release Mascot
 
on:
  release:
    types: [published]
 
permissions:
  contents: write
 
jobs:
  mascot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
 
      - name: Generate Release Mascot
        uses: OwainWilliams/OC.ReleaseMascot@main
        with:
          Tag: ${{ github.event.release.tag_name }}
